Milestone 1 components : Add Calculator
eroiyo/Math-magicians pull request #2
Opened 2021-08-18 06:32 UTC by eroiyo

Hello, in this update we have added a calculator, for the moment dont have the functions, but we have the layout
It features

*Calculator Component

-An Screen to display information
-19 buttons the white ones are numbers, the blues ones are for operations

the final size may vary depending on the final application's requirements

2021-08-18 06:47 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-18 06:47 UTC, arslanbisharat commented on src/App.js
> -export default App;
- [ ] Thank you for following the guidelines and deleting boilerplates but this file should not be deleted. It should have a class-based compoenet instead.

2021-08-18 06:47 UTC, arslanbisharat commented on src/components/Calculator.js
> +/* eslint-disable react/prefer-stateless-function */
- [ ] Please don't disable eslint rules. These are here to help us right the best quality of code.

2021-08-18 06:47 UTC, arslanbisharat commented on src/components/Calculator.js
> +const Calculator = class extends React.Component {
- [ ] [Optional] I would use a pureComponent here with ES6 syntax. 

```javascript
class Calculator extends Component {
  render() {
    // reference as a js object
    return {
      <div>
       // Calculator app design goes here
      </div>
    };
  }
}

export default Calculator;
```

2021-08-18 07:35 UTC, eroiyo commented on src/components/Calculator.js
> +const Calculator = class extends React.Component {
Thanks, i will be working on it

2021-08-18 07:36 UTC, eroiyo commented on src/App.js
> -export default App;
whats thats component do is display a React logo whirling around, I still have to have it in this project?

2021-08-18 09:32 UTC, Dipeshtwis requested changes
Hi @eroiyo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

_Check the comments under the review._

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 09:32 UTC, Dipeshtwis commented on src/App.js
> +  render();
- [ ] As told earlier, the `App` component should be a `class component` and not a functional component in this milestone. As we are trying to learn you all the concepts but one at a time. 
- [ ] You also need to import `React, {Component}` when you convert the functional component to class component extended from `React Component`.

2021-08-18 09:32 UTC, Dipeshtwis commented on src/components/Calculator.js
> +    return (
[OPTIONAL]

 - What the previous reviewer means to say with the `pure component` is that we will import components separately like this. You can follow the same strategy in `App` component as well.

```
import React, { Component } from 'react';
```

and use this in your code like this

Hint : 
```
class Calculator extends Component {
  render() {
    // reference as a js object
    return {
      <div>
       // Calculator app design goes here
      </div>
    };
  }
}

export default Calculator;
```

2021-08-18 09:56 UTC, Dipeshtwis commented on src/components/Calculator.js
> +    return (
> [OPTIONAL]
> 
> * What the previous reviewer means to say with the `pure component` is that we will import components separately like this. You can follow the same strategy in `App` component as well.
> 
> ```
> import React, { Component } from 'react';
> ```
> 
> and use this in your code like this
> 
> Hint :
> 
> ```
> class Calculator extends Component {
>   render() {
>     // reference as a js object
>     return {
>       <div>
>        // Calculator app design goes here
>       </div>
>     };
>   }
> }
> 
> export default Calculator;
> ```

Hi @eroiyo,

Sorry, this comment is misleading, and you did this right what the previous reviewer suggested. 

```
PureComponent can be used on classes with no states, the linter will otherwise give an error if you use the normal component.

```

Again, I have no intention to mislead you.
_Dipesh Kumar_

2021-08-18 10:01 UTC, eroiyo commented on src/components/Calculator.js
> +    return (
Thanks a lot!

2021-08-18 10:55 UTC, DeliceLydia approved these changes
# Congratulations🎉 🎉 

## Hi @eroiyo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 10:58 UTC, eroiyo commented
Thanks for the review all of you!, they are nice.

2021-08-18 10:59 UTC, merged

2021-08-19 11:29 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

I've spoken with CRs yesterday about this issue and solved it, but forgot to leave the comment,  Looks like everything was handled well and it got approved, good luck with the rest of the projects!

Keep rocking 🚀!